### ISSUE TITLE
pip install failed on macOS

### ISSUE THREAD

**Issue by srochel** [yuruofeifei/mms#14]
c4b301cf6ca3:Downloads steroche$ pip install mms
Collecting mms
  Downloading mms-0.1rc2.tar.gz (13.3MB)
    100% |████████████████████████████████| 13.3MB 20kB/s 
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/_5/vtwyq04d4zd3r54vybhc6v2n8qgblt/T/pip-build-g22lt675/mms/setup.py", line 3
        print find_packages(exclude=["tests", "build", "app", "models", "dist", "mms.egg-info"])
                          ^
    SyntaxError: invalid syntax
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/_5/vtwyq04d4zd3r54vybhc6v2n8qgblt/T/pip-build-g22lt675/mms/
c4b301cf6ca3:Downloads steroche$ python --version
Python 3.6.2 :: Anaconda, Inc.
c4b301cf6ca3:Downloads steroche$ pip install --upgrade pip
Requirement already up-to-date: pip in /Users/steroche/anaconda3/lib/python3.6/site-packages
c4b301cf6ca3:Downloads steroche$ pip install --upgrade setuptools
Requirement already up-to-date: setuptools in /Users/steroche/anaconda3/lib/python3.6/site-packages

**Comment by yuruofeifei** [comment]
For current phase, we are using python 2 as the development language but we are working to make it available for python3. 
If you want to do a quick test, can you try a python2 environment?

Thanks

**Comment by yuruofeifei** [comment]
I have fixed python2/3 incompatibility and pip3 should work now.
