### ISSUE TITLE
pip install mms returns No matching distribution found for mms

### ISSUE THREAD

**Issue by mattpairitz** [yuruofeifei/mms#20]
username@computer:/working/directory$ pip install mms
Collecting mms
  Could not find a version that satisfies the requirement mms (from versions: )
No matching distribution found for mms

**Comment by mattpairitz** [comment]
Get zip of repo, unzip, cd to root
```pip install -e .``` for local install. ```sudo``` may be required.

**Comment by sandeep-krishnamurthy** [comment]
@mattpairitz - Please see - https://github.com/awslabs/mxnet-model-server
